apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: vpa-demo-rollout
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vpa-demo-rollout
  template:
    metadata:
      labels:
        app: vpa-demo-rollout
    spec:
      containers:
      - name: vpa-demo-rollout
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "5m"       
            memory: "5Mi" 