apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: webapp
  endpoints:
    - port: web
