apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo
spec:
  selector:
    app: rollouts-demo # This should match the label selector of your Rollout
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
